object Versions {
    const val coroutines="1.7.3"
    const val loggingInterceptor="4.8.1"
    const  val moshiConverter= "2.9.0"
     const  val moshi ="1.13.0 "
    const  val gsonConverter="2.9.0"
    const val okhttp= "5.0.0-alpha.2"
    const  val retrofit= "2.9.0"
    const val hiltNavigationCompose="1.0.0"
    const val hiltCompiler="1.0.0-alpha01"
    const val hilt= "2.44.2"
    const val lifecycleViewModelKtx="androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
    const val navigationCompose= "2.7.0"
    const val compose = "2023.03.00"
    const val activityCompose = "1.7.2"
    const val lifecycleRuntimeKtx ="androidx.lifecycle:lifecycle-common:2.6.1"
    const val material="1.9.0"
    const val appcompat="1.6.1"
    const val coreKtx ="1.9.0"
}